rm(list=ls())
.libPaths(c("/storage/zhangyanxiaoLab/suzhuojie/R/x86_64-redhat-linux-gnu-library/4.2","/storage/zhangyanxiaoLab/suzhuojie/miniconda3/envs/R4.2/lib/R/library"))
setwd("/storage/zhangyanxiaoLab/suzhuojie/projects/medulloblastoma/")
library("beanplot")
library("mixtools")
library("pheatmap")
library("zoo")
library("squash")
library(Seurat)
set.seed(1)
library("biomaRt")
library("CONICSmat")
library(tricycle)
# s02_pri<-readRDS("data/merge_data/before_doubletfinder/annotation_rds/add_all_normal/s02_pri.rds")
# s02_rec<-readRDS("data/merge_data/before_doubletfinder/annotation_rds/add_all_normal/s02_rec.rds")
# BiocManager::install("infercnv")
sample <- C("s02_pri_rec","s04_pri_rec","s12_pri_rec")
se <- readRDS("data/merge_data/before_doubletfinder/annotation_rds/pair_annotation_final.rds")
se <- subset(se,cells=rownames(se@meta.data)[which(se$annotation %in% c("putative cancer"))])
pair <- GetAssayData(se,slot = "count")
# small <- readRDS("data/merge_data/before_doubletfinder/annotation_rds/add_all_normal/s02_pri_rec_merge.rds")
# small_pair <- GetAssayData(small,slot = "count")
# dim(small_pair)
suva_expr<-as.matrix(pair)
# suva_expr[1:5,1:5]
patients=strsplit(colnames(suva_expr),"_",fixed=TRUE)
patients<-as.data.frame(t(as.data.frame(patients)))
patients<-paste0(patients$V1,"_",patients$V2)
regions=read.table("/storage/zhangyanxiaoLab/suzhuojie/ref_data/chromosome_arm_positions_grch38.txt",sep="\t",row.names = 1,header = T)
head(regions,n=5)
gene_pos=getGenePositions(rownames(suva_expr),ensembl_version = "apr2022.archive.ensembl.org")
suva_expr=filterMatrix(suva_expr,gene_pos[,"hgnc_symbol"],minCells=5)
normFactor=calcNormFactors(suva_expr)
l=plotAll(suva_expr,normFactor,regions,gene_pos,"all_sample")
hi=plotHistogram(l,suva_expr,clusters=10,zscoreThreshold=1,patients)
